"""Config loader — the single place that knows where the template, inventory, schema,
catalog, and manifest live, and how to resolve an asset id to a file on disk.

Nothing here is Superba-specific: point TEMPLATE_PATH / the config JSONs at another
brand's files (regenerated by scripts/) and the whole pipeline retargets. That is the
"template-agnostic" contract from the spec.

MULTI-BRAND. Every lookup below is resolved for ONE brand, named by `brand` (a
ProductId from the frontend's app/products.ts). Superba is the default and keeps its
files exactly where they have always been — deck-service/{template.pptx,config/,assets/} —
so nothing about the live product moves. Every OTHER brand lives in a self-contained
directory, brands/<brand>/{template.pptx,config/,assets/}, with the same file names
inside. That asymmetry is deliberate: relocating Superba's assets would rewrite every
path in a shipping pipeline for a cosmetic gain.

A brand's config JSONs are GENERATED from its template by scripts/ (inspect -> manifest
-> schema), all of which take a --brand flag. See README.
"""
from __future__ import annotations

import functools
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent          # deck-service/
BRANDS_DIR = ROOT / "brands"
DEFAULT_BRAND = "superba"

CONFIG_DIR = ROOT / "config"                           # Superba's, i.e. the default brand's
ASSETS_DIR = ROOT / "assets"


def brand_root(brand: str | None = None) -> Path:
    """The directory holding one brand's template, config/ and assets/."""
    return ROOT if not brand or brand == DEFAULT_BRAND else BRANDS_DIR / brand


def config_dir(brand: str | None = None) -> Path:
    return brand_root(brand) / "config"


def assets_dir(brand: str | None = None) -> Path:
    return brand_root(brand) / "assets"


def known_brands() -> list[str]:
    """Brands this service can actually render: the default plus every brands/<id>/
    directory carrying a template. Purely filesystem-derived, so adding a brand pack is
    a deploy, not a code change."""
    extra = sorted(
        p.name for p in BRANDS_DIR.iterdir()
        if p.is_dir() and (p / "template.pptx").exists()
    ) if BRANDS_DIR.exists() else []
    return [DEFAULT_BRAND, *extra]


# The real template lives under the (gitignored) brand pack locally; on deploy a copy is
# committed at deck-service/template.pptx. Env override wins so the corporate template can
# be swapped in without code changes.
_DEFAULT_TEMPLATES = [
    ROOT / "template.pptx",
    ROOT / "brand_assets" / "05. Superba Brand Identity" / "Superba refresh power point template.pptx",
]

# Content model. Defaults to claude-sonnet-5; overridable via DECK_MODEL (e.g. claude-opus-4-8
# or a pinned dated version) without a code change. API key comes from ANTHROPIC_API_KEY only.
MODEL = os.environ.get("DECK_MODEL", "claude-sonnet-5")

SLIDE_TARGETS = {"kort": 9, "standard": 15, "detaljert": 19, "omfattende": 26}


def template_path(brand: str | None = None) -> Path:
    # DECK_TEMPLATE is a DEFAULT-BRAND override only. It predates multi-brand and exists so
    # the corporate Superba template can be swapped in on a deploy; letting it apply to every
    # brand would silently render Revervia onto whatever that variable points at.
    if not brand or brand == DEFAULT_BRAND:
        env = os.environ.get("DECK_TEMPLATE")
        if env:
            return Path(env)
        for p in _DEFAULT_TEMPLATES:
            if p.exists():
                return p
        return _DEFAULT_TEMPLATES[0]
    return brand_root(brand) / "template.pptx"


@functools.lru_cache(maxsize=None)
def _load(name: str, brand: str | None = None) -> dict:
    """Cached per (name, brand) — the cache key includes the brand on purpose. One process
    serves every brand, so a single-key cache would hand Superba's schema to Revervia."""
    return json.loads((config_dir(brand) / name).read_text(encoding="utf-8"))


def inventory(brand: str | None = None) -> dict:
    return _load("template_inventory.json", brand)


def schema(brand: str | None = None) -> dict:
    return _load("slide_schema.json", brand)


def catalog(brand: str | None = None) -> dict:
    return _load("layout_catalog.json", brand)


def manifest(brand: str | None = None) -> dict:
    return _load("asset_manifest.json", brand)


@functools.lru_cache(maxsize=None)
def asset_index(brand: str | None = None) -> dict:
    """id -> manifest entry."""
    return {a["id"]: a for a in manifest(brand)["assets"]}


def resolve_asset(rel_path: str, brand: str | None = None) -> Path:
    """A manifest path is relative to its OWN brand's root; make it absolute."""
    return (brand_root(brand) / rel_path).resolve()


def selectable_photos(brand: str | None = None) -> list[dict]:
    return [a for a in manifest(brand)["assets"] if a.get("selectable") and a["kind"] == "photo"]


@functools.lru_cache(maxsize=None)
def figures_index(brand: str | None = None) -> dict:
    """pmid -> [{file, page, width, height, kind}], written by scripts/extract_figures.py. Empty dict
    if it hasn't been generated yet (a fresh checkout, or before any PDFs were supplied).

    Study figures are PubMed-keyed science, not brand design, and only the default brand has a
    study library today — a brand without an index simply gets no appendix."""
    p = assets_dir(brand) / "figures" / "index.json"
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}


def figure_path(pmid: str, filename: str, brand: str | None = None) -> Path:
    return assets_dir(brand) / "figures" / pmid / filename
