"""Config loader — the single place that knows where the template, inventory, schema,
catalog, and manifest live, and how to resolve an asset id to a file on disk.

Nothing here is Superba-specific: point TEMPLATE_PATH / the config JSONs at another
brand's files (regenerated by scripts/) and the whole pipeline retargets. That is the
"template-agnostic" contract from the spec.
"""
from __future__ import annotations

import functools
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent          # deck-service/
CONFIG_DIR = ROOT / "config"
ASSETS_DIR = ROOT / "assets"

# The real template lives under the (gitignored) brand pack locally; on deploy a copy is
# committed at deck-service/template.pptx. Env override wins so the corporate template can
# be swapped in without code changes.
_DEFAULT_TEMPLATES = [
    ROOT / "template.pptx",
    ROOT / "brand_assets" / "05. Superba Brand Identity" / "Superba refresh power point template.pptx",
]

# Content model. Defaults to claude-sonnet-5; overridable via DECK_MODEL (e.g. claude-opus-4-8
# or a pinned dated version) without a code change. API key comes from ANTHROPIC_API_KEY only.
MODEL = os.environ.get("DECK_MODEL", "claude-sonnet-5")

SLIDE_TARGETS = {"kort": 6, "standard": 9, "detaljert": 13}


def template_path() -> Path:
    env = os.environ.get("DECK_TEMPLATE")
    if env:
        return Path(env)
    for p in _DEFAULT_TEMPLATES:
        if p.exists():
            return p
    return _DEFAULT_TEMPLATES[0]


@functools.lru_cache(maxsize=None)
def _load(name: str) -> dict:
    return json.loads((CONFIG_DIR / name).read_text(encoding="utf-8"))


def inventory() -> dict:
    return _load("template_inventory.json")


def schema() -> dict:
    return _load("slide_schema.json")


def catalog() -> dict:
    return _load("layout_catalog.json")


def manifest() -> dict:
    return _load("asset_manifest.json")


@functools.lru_cache(maxsize=None)
def asset_index() -> dict:
    """id -> manifest entry."""
    return {a["id"]: a for a in manifest()["assets"]}


def resolve_asset(rel_path: str) -> Path:
    """A manifest path is relative to the deck-service root; make it absolute."""
    return (ROOT / rel_path).resolve()


def selectable_photos() -> list[dict]:
    return [a for a in manifest()["assets"] if a.get("selectable") and a["kind"] == "photo"]
