"""IDML whitepaper fill — the InDesign analog of the pptx template-fill.

`assets/whitepaper_template.idml` is AKBM's real Healthy Aging whitepaper (a designed,
finished InDesign document). `config/idml_manifest.json` (generated by
scripts/build_idml_manifest.py) maps its text stories to semantic slots with per-line
character budgets derived from the text each frame actually holds today.

The fill NEVER touches XML structure: it only rewrites the text inside existing <Content>
nodes, line by line (a "line" = the Content runs between <Br/> elements). Bullet markers
("•" runs) and leading tabs are preserved; paragraph styles, threading, images, geometry
and the whole design are inherited untouched — the exact contract the deck renderer has
with template.pptx. Content is capped to each line's budget, not shrunk.

No headless IDML renderer exists (InDesign Server is paid), so there is no visual QA gate
here; safety is deterministic: schema-fixed slot counts + budgets measured from the template.
"""
from __future__ import annotations

import datetime
import functools
import io
import json
import re
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

from . import config

MANIFEST_PATH = config.CONFIG_DIR / "idml_manifest.json"

IDML_MEDIA = "application/vnd.adobe.indesign-idml-package"

# Prepended to the legal note on the back page — the visible AI disclaimer the house rules
# require on every generated asset. Kept short to limit overset risk in the fixed frame.
AI_NOTE = "AI GENERATED DRAFT. Review all content, claims and figures before any use."

_MARKER_RE = re.compile(r"^[\s•·▪‣﻿ ]*$")  # bullet/space-only runs
_NS = "http://ns.adobe.com/AdobeInDesign/idml/1.0/packaging"
ET.register_namespace("idPkg", _NS)


@functools.lru_cache(maxsize=None)
def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def template_idml_path() -> Path:
    return (config.ROOT / load_manifest()["template"]).resolve()


# ---------------------------------------------------------------------------
# Story text model: a story is a sequence of LINES; a line is the list of <Content>
# elements between <Br/> elements (in document order, across style ranges).
# ---------------------------------------------------------------------------

def story_lines(root: ET.Element) -> list[list[ET.Element]]:
    lines: list[list[ET.Element]] = []
    cur: list[ET.Element] = []
    for el in root.iter():
        tag = el.tag.rsplit("}", 1)[-1]
        if tag == "Content":
            cur.append(el)
        elif tag == "Br":
            lines.append(cur)
            cur = []
    lines.append(cur)
    return lines


def line_text(line: list[ET.Element]) -> str:
    return "".join(c.text or "" for c in line)


def payload_lines(root: ET.Element) -> list[list[ET.Element]]:
    """Lines that carry real text (not empty spacers, not bullet-marker-only runs)."""
    return [ln for ln in story_lines(root) if not _MARKER_RE.fullmatch(line_text(ln) or "")]


def payload_text(line: list[ET.Element]) -> str:
    """A line's text minus any leading bullet marker/tab prefix (what the budget measures)."""
    return re.sub(r"^[\s•·▪‣﻿]+", "", line_text(line))


def set_line(line: list[ET.Element], text: str) -> None:
    """Write `text` into a line, keeping bullet-marker runs and the leading tab intact."""
    wrote = False
    for c in line:
        t = c.text or ""
        if not wrote and _MARKER_RE.fullmatch(t):
            continue  # keep the "•" marker run untouched
        if not wrote:
            lead = re.match(r"[\s﻿]*", t).group(0)
            c.text = lead + text
            wrote = True
        else:
            c.text = ""
    if not wrote and line:  # marker-only line (shouldn't happen for payload lines)
        line[-1].text = (line[-1].text or "") + text


def truncate(text: str, cap: int) -> str:
    """Cap, not shrink: cut at the last sentence end (else word end) under the budget."""
    text = (text or "").strip()
    if len(text) <= cap:
        return text
    cut = text[:cap]
    dot = cut.rfind(". ")
    if dot > cap * 0.5:
        return cut[: dot + 1]
    sp = cut.rfind(" ")
    return (cut[:sp] if sp > 0 else cut).rstrip(",;: ")


# ---------------------------------------------------------------------------
# Serialization — byte-faithful except for the Content text we changed.
# ---------------------------------------------------------------------------

def _parse_story(data: bytes) -> ET.Element:
    return ET.fromstring(data.decode("utf-8"))


def _serialize_story(root: ET.Element) -> bytes:
    body = ET.tostring(root, encoding="unicode")
    return ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' + body).encode("utf-8")


# ---------------------------------------------------------------------------
# Fill engine
# ---------------------------------------------------------------------------

def _strip_dashes(s: str) -> str:
    from .blog import strip_dashes  # late import to avoid cycles
    return strip_dashes(s)


def _fill_story_texts(xml: bytes, texts: list[str], caps: list[int]) -> bytes:
    """Map `texts` onto the story's payload lines 1:1; blank leftover lines; merge overflow
    items into the last text so nothing is silently dropped."""
    root = _parse_story(xml)
    lines = payload_lines(root)
    if not lines:
        return xml
    if len(texts) > len(lines):
        head, tail = texts[: len(lines) - 1], texts[len(lines) - 1:]
        texts = head + [" ".join(t for t in tail if t)]
    for i, ln in enumerate(lines):
        if i < len(texts):
            cap = caps[i] if i < len(caps) else (caps[-1] if caps else 400)
            set_line(ln, truncate(_strip_dashes(texts[i] or ""), cap))
        else:
            set_line(ln, "")
    return _serialize_story(root)


def _slot_texts(slot: dict, value) -> list[str]:
    """Normalize a plan value for a slot into the list of line texts."""
    if value is None:
        return []
    if slot["mode"] == "single":
        return [str(value)]
    if isinstance(value, str):  # prose emitted as one string -> split paragraphs
        return [p.strip() for p in re.split(r"\n\s*\n|\n", value) if p.strip()]
    return [str(v) for v in value]


def _iter_slots(manifest: dict, plan: dict):
    """Yield (slot_dict, plan_value) pairs for every slot in the manifest tree."""
    groups = manifest["groups"]

    def slots_of(group: dict, values: dict):
        for key, slot in (group.get("slots") or {}).items():
            yield slot, (values or {}).get(key)

    for name in ("cover", "intro", "conclusion", "cta"):
        yield from slots_of(groups[name], plan.get(name) or {})

    rt = groups["running_topic"]
    for sid in rt["stories"]:
        yield ({"story": sid, "mode": "single", "lines": [{"cap": rt["cap"]}]},
               plan.get("running_topic"))

    for skey, section in groups["sections"]["sections"].items():
        pvals = (plan.get("sections") or {}).get(skey) or {}
        yield from slots_of(section, pvals)
        cards = pvals.get("cards") or []
        for i, card in enumerate(section.get("cards") or []):
            cval = cards[i] if i < len(cards) else {}
            yield card["header"], cval.get("year_author")
            body_texts = [cval.get("title") or "", cval.get("design") or "",
                          cval.get("meta") or ""] + list(cval.get("findings") or [])
            yield card["body"], (body_texts if cval else None)
            doses = cval.get("doses") or []
            for j, dslot in enumerate(card.get("doses") or []):
                yield dslot, (doses[j] if j < len(doses) else "")


def fill_idml(plan: dict, template_path: Path | None = None) -> bytes:
    """Fill the whitepaper template's stories from the structured plan -> .idml bytes."""
    manifest = load_manifest()
    tpl = Path(template_path) if template_path else template_idml_path()
    zin = zipfile.ZipFile(io.BytesIO(tpl.read_bytes()))

    changed: dict[str, bytes] = {}

    def member(sid: str) -> str:
        return f"Stories/Story_{sid}.xml"

    def fill(sid: str, texts: list[str], caps: list[int]):
        name = member(sid)
        src = changed.get(name) or zin.read(name)
        changed[name] = _fill_story_texts(src, texts, caps)

    # Every MAPPED slot is either filled from the plan OR blanked. Original template text is
    # NEVER left behind in a fillable region — otherwise a partial plan would ship a document
    # that looks finished but still carries the wrong (template) content. Locked/unmapped
    # stories are untouched by construction (they are never yielded here).
    for slot, value in _iter_slots(manifest, plan):
        texts = _slot_texts(slot, value)
        caps = [ln["cap"] for ln in slot.get("lines") or []]
        if texts:
            fill(slot["story"], texts, caps)
        else:
            n = len(slot.get("lines") or []) or 1
            fill(slot["story"], [""] * n, [10] * n)

    # Deterministic extras: edition line + the AI disclaimer on the back page.
    year = datetime.date.today().year
    for sid in manifest.get("edition_stories") or []:
        fill(sid, [f"White Paper {year}"], [24])
    dis = manifest.get("disclaimer_story")
    if dis:
        name = member(dis)
        root = _parse_story(changed.get(name) or zin.read(name))
        lines = payload_lines(root)
        if lines:
            set_line(lines[0], AI_NOTE + " " + payload_text(lines[0]))
            changed[name] = _serialize_story(root)

    # Repack: mimetype first & stored (zip-container convention), all else as-is.
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zout:
        names = zin.namelist()
        if "mimetype" in names:
            zout.writestr(zipfile.ZipInfo("mimetype"), zin.read("mimetype"),
                          compress_type=zipfile.ZIP_STORED)
        for n in names:
            if n == "mimetype":
                continue
            zout.writestr(n, changed.get(n, zin.read(n)))
    return out.getvalue()


# ---------------------------------------------------------------------------
# Planner-facing schema — generated from the manifest, like build_schema.py for slides.
# ---------------------------------------------------------------------------

def _slot_schema(slot: dict, what: str) -> dict:
    caps = [ln["cap"] for ln in slot.get("lines") or [{"cap": 200}]]
    sample = (slot.get("sample") or "")[:90]
    desc = f"{what} Budget per line: {caps} chars."
    if sample:
        desc += f' Role example from the current document (NEVER copy it): "{sample}"'
    if slot["mode"] == "single":
        return {"type": "string", "maxLength": max(caps[0], 10), "description": desc}
    return {"type": "array", "minItems": 1, "maxItems": len(caps),
            "items": {"type": "string", "maxLength": max(max(caps), 40)},
            "description": desc + f" Exactly up to {len(caps)} lines/paragraphs."}


def _card_schema(cards: list[dict]) -> dict:
    """One shared schema for a section's cards, sized to the section's ROOMIEST card; the
    fill engine drops what an individual card cannot hold, so a mismatch degrades, never fails."""
    card = max(cards, key=lambda c: len(c["body"].get("lines") or []))
    n_lines = len(card["body"].get("lines") or [])
    caps = [ln["cap"] for ln in card["body"].get("lines") or []]
    findings_max = max(1, n_lines - 3)
    dose_caps = [len(c.get("doses") or []) for c in cards]
    return {
        "type": "object", "additionalProperties": False,
        "required": ["year_author", "title", "design", "meta", "findings", "doses"],
        "properties": {
            "year_author": {"type": "string", "maxLength": max(card["header"]["lines"][0]["cap"], 18),
                            "description": 'Year + lead author, e.g. "2022 STONEHOUSE".'},
            "title": {"type": "string", "maxLength": max(caps[0] if caps else 160, 60),
                      "description": "The paper's title (journal style, italic in the design)."},
            "design": {"type": "string", "maxLength": max(caps[1] if len(caps) > 1 else 90, 60),
                       "description": 'Study design line, e.g. "Published randomized, double blind, placebo controlled trial".'},
            "meta": {"type": "string", "maxLength": max(caps[2] if len(caps) > 2 else 90, 60),
                     "description": 'Location / time frame / subjects, e.g. "Location: US. Time frame: 27 wks. Subjects: 520 adults".'},
            "findings": {"type": "array", "minItems": 1, "maxItems": findings_max,
                         "items": {"type": "string", "maxLength": max((max(caps[3:]) if len(caps) > 3 else 120), 60)},
                         "description": f"Key results WITH the real numbers from the source. Up to {findings_max} short bullet lines."},
            "doses": {"type": "array", "minItems": 0, "maxItems": max(dose_caps or [0]),
                      "items": {"type": "string", "maxLength": 90},
                      "description": (f'One line per study arm, e.g. "Dose: 4 g/day of Krill oil (885 mg EPA, 354 mg DHA)". '
                                      f"The section's cards hold {dose_caps} dose lines respectively (in order); "
                                      f"place studies with many arms on the roomier cards.")},
        },
    }


def build_idml_schema() -> dict:
    m = load_manifest()
    g = m["groups"]

    def group_schema(group: dict, what: dict) -> dict:
        props = {k: _slot_schema(s, what.get(k, "")) for k, s in (group.get("slots") or {}).items()}
        return {"type": "object", "additionalProperties": False,
                "required": list(props), "properties": props}

    sections_props = {}
    for skey, section in g["sections"]["sections"].items():
        sec = group_schema(section, section.get("hints") or {})
        sec["properties"]["cards"] = {
            "type": "array", "minItems": 1, "maxItems": len(section.get("cards") or []),
            "items": _card_schema(section["cards"]) if section.get("cards") else {"type": "object"},
            "description": (f"Trial summary cards, one per human clinical trial from the source, in order. "
                            f"This section's page(s) hold up to {len(section.get('cards') or [])} cards; "
                            f"emit only as many as the source truly supports."),
        }
        sec["required"].append("cards")
        sections_props[skey] = sec
        sections_props[skey]["description"] = section.get("topic_hint", "")

    return {
        "type": "object", "additionalProperties": False,
        "required": ["cover", "running_topic", "intro", "sections", "conclusion", "cta"],
        "properties": {
            "cover": group_schema(g["cover"], {"title": "Whitepaper title.",
                                               "subtitle": "Short evocative subtitle.",
                                               "hero": "One sentence: what this whitepaper shows."}),
            "running_topic": {"type": "string", "maxLength": g["running_topic"]["cap"],
                              "description": 'Running page header naming the research area, e.g. "Healthy Aging Research".'},
            "intro": group_schema(g["intro"], {}),
            "sections": {"type": "object", "additionalProperties": False,
                         "required": list(sections_props), "properties": sections_props},
            "conclusion": group_schema(g["conclusion"], {}),
            "cta": group_schema(g["cta"], {"text": "Closing call to action to contact Aker BioMarine."}),
        },
    }


# ---------------------------------------------------------------------------
# Markdown preview of the filled document (shown in the UI next to the .idml download).
# ---------------------------------------------------------------------------

def idml_plan_to_markdown(plan: dict) -> str:
    from .blog import strip_dashes
    parts: list[str] = []
    cov = plan.get("cover") or {}
    if cov.get("title"):
        parts.append(f"# {cov['title']}")
    if cov.get("subtitle"):
        parts.append(f"*{cov['subtitle']}*")
    if cov.get("hero"):
        parts.append(f"**{cov['hero']}**")

    def prose(v):
        return "\n\n".join(v) if isinstance(v, list) else str(v or "")

    intro = plan.get("intro") or {}
    if intro.get("title"):
        parts.append(f"## {prose(intro['title'])}")
    for k in ("lead", "body_1", "body_2"):
        if intro.get(k):
            parts.append(prose(intro[k]))

    for skey, sec in (plan.get("sections") or {}).items():
        title = sec.get("benefits_title") or sec.get("page_topic") or skey
        parts.append(f"## {prose(title) if not isinstance(title, list) else ' '.join(title)}")
        for k, v in sec.items():
            if k in ("cards", "benefits_title", "page_topic") or not v:
                continue
            if isinstance(v, list) and k.startswith("benefits"):
                parts += [f"- {b}" for b in v]
            else:
                parts.append(prose(v))
        for c in sec.get("cards") or []:
            parts.append(f"### {c.get('year_author', '')}: {c.get('title', '')}")
            body = " ".join(x for x in (c.get("design"), c.get("meta")) if x)
            if body:
                parts.append(body)
            parts += [f"- {f}" for f in c.get("findings") or []]
            parts += [f"- {d}" for d in c.get("doses") or []]

    conc = plan.get("conclusion") or {}
    if conc:
        parts.append("## Conclusion")
        for v in conc.values():
            if v:
                parts.append(prose(v))
    cta = (plan.get("cta") or {}).get("text")
    if cta:
        parts.append("## Next steps")
        parts.append(cta)
    return strip_dashes("\n\n".join(p for p in parts if p and str(p).strip()))
