// Mock payload for the Data Warehouse preview tab, transcribed verbatim from AKBM's
// "krill_oil_evidence_database_v4.xlsx" solution design (received 2026-08-10). AKBM's real
// data warehouse does not exist yet -- this is the client's OWN proposed schema and sample
// content, used here to preview the UX before a real API exists. Andersen et al. (2026) is
// explicitly marked in the client's file as a FICTIVE protocol for marketing development only.

export type WarehouseStudy = {
  reference: string;
  journal: string;
  year: number;
  studyType: string;
  country: string;
  population: string;
  n: number | string;
  meanAge: string;
  intervention: string;
  dose: string;
  comparator: string;
  duration: string;
  primaryOutcome: string;
  secondaryOutcomes: string;
  biomarkerSubStudy: string;
  keyResult: string;
  fundingSource: string;
  blinding: string;
  allocationConcealment: string;
  randomisation: string;
  ittAnalysis: string;
  dropoutReported: string;
  trialRegistration: string;
  sampleSizeCalc: string;
  fundingTransparency: string;
  qualityScore: number;
  qualityRating: "Low" | "Moderate" | "High";
  limitations: string;
  fictive: boolean;
  /** AKBM's own benefit categories (see CATEGORIES in ../studies), not part of the client's Excel. */
  categories: string[];
};

export type WarehouseResult = {
  study: string;
  journal: string;
  year: number;
  n: number | string;
  dose: string;
  duration: string;
  outcomeMeasure: string;
  timepoint: string;
  krillOilResult: string;
  placeboResult: string;
  statisticalResult: string;
  significance: "Significant" | "Not Significant" | "Not Significant (transient)" | "Pending";
};

export type WarehouseOutcome = {
  study: string;
  year: number;
  n: number | string;
  population: string;
  dose: string;
  duration: string;
  primaryOutcomeMeasure: string;
  directionOfEffect: string;
  pValue: string;
  conclusion: string;
};

export type WarehouseQualityCriterion = {
  criterion: string;
  values: Record<string, string | number>;
};

export const WAREHOUSE_STUDIES: WarehouseStudy[] = [
  {
    reference: "Deutsch (2007)",
    journal: "J Am Coll Nutr",
    year: 2007,
    studyType: "RCT",
    country: "Canada",
    population: "Adults with CVD, RA or OA and elevated CRP (>1.0 mg/dL)",
    n: 90,
    meanAge: "NR (mean ~55 yrs)",
    intervention: "Neptune Krill Oil (NKO™)",
    dose: "300 mg/day",
    comparator: "Placebo",
    duration: "30 days",
    primaryOutcome: "CRP levels and WOMAC arthritic symptoms (pain, stiffness, functional impairment)",
    secondaryOutcomes: "Acetaminophen (NSAID) use",
    biomarkerSubStudy: "None",
    keyResult: "Significant reductions in CRP (−29.7% at day 14, p<0.001) and all WOMAC domains from day 7 vs placebo",
    fundingSource: "Unclear (industry likely)",
    blinding: "Double-blind",
    allocationConcealment: "Not reported",
    randomisation: "Reported",
    ittAnalysis: "Not reported",
    dropoutReported: "Not reported",
    trialRegistration: "Not reported",
    sampleSizeCalc: "Not reported",
    fundingTransparency: "Not reported",
    qualityScore: 25,
    qualityRating: "Low",
    limitations: "Small heterogeneous sample; short duration; limited methodological reporting; high risk of bias",
    fictive: false,
    categories: ["Wellness & Immune Support", "Joint Support"], // per ARCHIVE_CATEGORIES (PMID 17353582)
  },
  {
    reference: "Suzuki et al. (2016)",
    journal: "PLoS ONE",
    year: 2016,
    studyType: "RCT",
    country: "Japan",
    population: "Adults (38–85 yrs) with mild knee pain not requiring pharmacotherapy",
    n: 50,
    meanAge: "~64 yrs (mean)",
    intervention: "Superba™ Krill Oil",
    dose: "2 g/day (240 mg EPA + 110 mg DHA)",
    comparator: "Identical placebo (safflower oil)",
    duration: "30 days",
    primaryOutcome: "Subjective knee symptoms: JKOM questionnaire and JOA score",
    secondaryOutcomes: "Plasma fatty acids (EPA, DHA, AA); CRP; MMP-3; hyaluronic acid; blood count; liver and kidney function",
    biomarkerSubStudy: "Plasma fatty acid profile (EPA, DHA, AA, di-homo-γ-linoleic acid)",
    keyResult: "Significant improvements in night pain and pain on standing (JKOM); range of motion (JOA); increased plasma EPA",
    fundingSource: "Sunsho Pharmaceutical Co. (supplements only)",
    blinding: "Double-blind",
    allocationConcealment: "Not clearly described",
    randomisation: "Reported (sealed opaque envelopes)",
    ittAnalysis: "Not reported (per-protocol)",
    dropoutReported: "3 withdrew (placebo); 47 analysed",
    trialRegistration: "UMIN-CTR UMIN000014413",
    sampleSizeCalc: "Not reported",
    fundingTransparency: "Declared; funders had no role in analysis",
    qualityScore: 63,
    qualityRating: "Moderate",
    limitations: "Small sample; short duration; non-ITT analysis; Japanese-specific tools; single site; industry funded",
    fictive: false,
    categories: ["Joint Support"], // per ARCHIVE_CATEGORIES (PMID 27701428)
  },
  {
    reference: "Stonehouse et al. (2022)",
    journal: "Am J Clin Nutr",
    year: 2022,
    studyType: "RCT",
    country: "Australia",
    population: "Adults (40–75 yrs) with mild-to-moderate knee OA (VAS 4–8/10)",
    n: 235,
    meanAge: "~57 yrs (mean)",
    intervention: "Aker BioMarine krill oil",
    dose: "4 g/day (~0.60 g EPA + 0.28 g DHA + 0.45 mg astaxanthin)",
    comparator: "Matched placebo (mixed vegetable oil)",
    duration: "6 months",
    primaryOutcome: "Change in WOMAC knee pain score (0–100) at 6 months",
    secondaryOutcomes: "WOMAC stiffness and function; Omega-3 Index; serum lipids; hsCRP; IL-6; TNF-α; NSAID use; safety",
    biomarkerSubStudy: "Omega-3 Index; serum hsCRP, IL-6, TNF-α; lipid panel",
    keyResult: "WOMAC pain MD −5.18 (95% CI −10.0 to −0.32; p=0.04); stiffness p=0.001; function p<0.05; Omega-3 Index 6.0%→8.9%",
    fundingSource: "NHMRC + Aker BioMarine (supplements only; independent analysis)",
    blinding: "Double-blind; statisticians blinded",
    allocationConcealment: "Centralised IVRS minimisation; opaque identical containers",
    randomisation: "Minimisation via IVRS; stratified by site, sex, pain, age",
    ittAnalysis: "Yes — pre-specified ITT (ANCOVA) + per-protocol",
    dropoutReported: "24/235 (10.2%); reasons documented",
    trialRegistration: "ClinicalTrials.gov NCT03483090",
    sampleSizeCalc: "Yes — 238 participants for 80% power",
    fundingTransparency: "Declared; industry supplements only",
    qualityScore: 100,
    qualityRating: "High",
    limitations: "Normo- to borderline hyperlipidaemic population; MCID for WOMAC uncertain; no effusion-synovitis criterion",
    fictive: false,
    categories: ["Joint Support", "Healthy Aging Support"], // per ARCHIVE_CATEGORIES (PMID 35880828)
  },
  {
    reference: "Laslett et al. (2024)",
    journal: "JAMA",
    year: 2024,
    studyType: "RCT",
    country: "Australia",
    population: "Adults ≥40 yrs with clinical knee OA, significant pain and MRI-confirmed effusion-synovitis",
    n: 262,
    meanAge: "NR (≥40 yrs)",
    intervention: "Krill oil",
    dose: "2 g/day",
    comparator: "Identical placebo",
    duration: "24 weeks",
    primaryOutcome: "Change in VAS knee pain (0–100) over 24 weeks",
    secondaryOutcomes: "MRI effusion-synovitis volume; WOMAC subscales; Omega-3 Index; serum lipids; inflammatory markers; safety",
    biomarkerSubStudy: "MRI effusion-synovitis volume; Omega-3 Index; serum inflammatory markers",
    keyResult: "No significant difference in VAS knee pain vs placebo (MD 0.30; 95% CI −6.9 to 6.4; p=0.94)",
    fundingSource: "NHMRC + University of Tasmania; Aker BioMarine (supplements only)",
    blinding: "Double-blind",
    allocationConcealment: "Centralised; identical opaque containers",
    randomisation: "Yes — multicentre, 5 Australian cities",
    ittAnalysis: "Yes — pre-specified ITT",
    dropoutReported: "24/262 (9.2%); documented",
    trialRegistration: "ACTRN12616001351493",
    sampleSizeCalc: "Yes (pre-specified from protocol)",
    fundingTransparency: "Declared; industry supplements only",
    qualityScore: 100,
    qualityRating: "High",
    limitations: "Only tested 2 g/day; effusion-synovitis criterion limits generalisability; does not rule out benefit at higher doses",
    fictive: false,
    categories: ["Joint Support"], // per ARCHIVE_CATEGORIES (PMID 38776073, KARAOKE 2024 results)
  },
  {
    reference: "Andersen et al. (2026)*",
    journal: "Protocol — FICTIVE",
    year: 2026,
    studyType: "Protocol (fictive)",
    country: "Norway / Denmark",
    population: "Adults (45–75 yrs) with early-to-moderate knee OA, elevated hsCRP (1–10 mg/L) and MRI-confirmed synovial thickening",
    n: "320 (target)",
    meanAge: "Target ~58 yrs",
    intervention: "Superba™ Krill Oil",
    dose: "4 g/day (~0.8 g EPA + 0.36 g DHA, phospholipid-bound)",
    comparator: "Matched placebo (high-oleic sunflower oil)",
    duration: "12 months",
    primaryOutcome: "Change in WOMAC knee pain score (0–100) at 12 months",
    secondaryOutcomes: "WOMAC stiffness and function; VAS; ICOAP; patient global assessment; NSAID use; Omega-3 Index; hsCRP, IL-6, TNF-α, MMP-3; EQ-5D-5L; safety",
    biomarkerSubStudy: "MRI synovial volume and effusion (baseline, 6 and 12 months); serum hsCRP, IL-6, TNF-α, MMP-3 (baseline, 3, 6 and 12 months); Omega-3 Index (baseline, 6 and 12 months)",
    keyResult: "Protocol only — no results. Powered to detect MCID ≥15 points with 90% power.",
    fundingSource: "Aker BioMarine AS (full sponsorship)",
    blinding: "Double-blind",
    allocationConcealment: "Centralised IWRS; stratified",
    randomisation: "1:1 minimisation",
    ittAnalysis: "Pre-specified ITT + per-protocol sensitivity",
    dropoutReported: "20% assumed; withdrawal rules pre-specified",
    trialRegistration: "ClinicalTrials.gov (pending)",
    sampleSizeCalc: "Yes — 320 for 90% power (MCID 15, SD 30, α=0.05, 20% dropout)",
    fundingTransparency: "Full industry sponsorship declared; sponsor involved in design",
    qualityScore: 88,
    qualityRating: "High",
    limitations: "FICTIVE PROTOCOL — not a real study. Full industry sponsorship with design involvement is a potential source of bias.",
    fictive: true,
    categories: ["Joint Support"], // not in ARCHIVE_CATEGORIES (fictive); assigned by the same knee/OA content judgment as the fallback keyword rule in ../studies.ts
  },
];

export const WAREHOUSE_RESULTS: WarehouseResult[] = [
  {
    study: "Deutsch (2007)",
    journal: "J Am Coll Nutr",
    year: 2007,
    n: 90,
    dose: "300 mg/day",
    duration: "30 days",
    outcomeMeasure: "CRP",
    timepoint: "Day 7",
    krillOilResult: "−19.3% (mean 2.01 mg/dL)",
    placeboResult: "+15.7% (mean 3.32 mg/dL)",
    statisticalResult: "p = 0.049",
    significance: "Significant",
  },
  {
    study: "Deutsch (2007)",
    journal: "J Am Coll Nutr",
    year: 2007,
    n: 90,
    dose: "300 mg/day",
    duration: "30 days",
    outcomeMeasure: "CRP",
    timepoint: "Day 14",
    krillOilResult: "−29.7% (mean 1.75 mg/dL)",
    placeboResult: "+32.1% (mean 3.79 mg/dL)",
    statisticalResult: "p = 0.004",
    significance: "Significant",
  },
  {
    study: "Deutsch (2007)",
    journal: "J Am Coll Nutr",
    year: 2007,
    n: 90,
    dose: "300 mg/day",
    duration: "30 days",
    outcomeMeasure: "CRP",
    timepoint: "Day 30",
    krillOilResult: "−30.9% (mean 1.72 mg/dL)",
    placeboResult: "+25.1% (mean 3.59 mg/dL)",
    statisticalResult: "p = 0.008",
    significance: "Significant",
  },
  {
    study: "Deutsch (2007)",
    journal: "J Am Coll Nutr",
    year: 2007,
    n: 90,
    dose: "300 mg/day",
    duration: "30 days",
    outcomeMeasure: "WOMAC Pain",
    timepoint: "Day 7",
    krillOilResult: "−28.9% (mean 2.41)",
    placeboResult: "−9.4% (mean 2.78)",
    statisticalResult: "p = 0.050",
    significance: "Significant",
  },
  {
    study: "Deutsch (2007)",
    journal: "J Am Coll Nutr",
    year: 2007,
    n: 90,
    dose: "300 mg/day",
    duration: "30 days",
    outcomeMeasure: "WOMAC Pain",
    timepoint: "Day 14",
    krillOilResult: "−25.7% (mean 2.52)",
    placeboResult: "+6.2% (mean 3.26)",
    statisticalResult: "p = 0.003",
    significance: "Significant",
  },
  {
    study: "Deutsch (2007)",
    journal: "J Am Coll Nutr",
    year: 2007,
    n: 90,
    dose: "300 mg/day",
    duration: "30 days",
    outcomeMeasure: "WOMAC Pain",
    timepoint: "Day 30",
    krillOilResult: "−38.4% (mean 2.09)",
    placeboResult: "−0.6% (mean 3.05)",
    statisticalResult: "p = 0.009",
    significance: "Significant",
  },
  {
    study: "Deutsch (2007)",
    journal: "J Am Coll Nutr",
    year: 2007,
    n: 90,
    dose: "300 mg/day",
    duration: "30 days",
    outcomeMeasure: "WOMAC Stiffness",
    timepoint: "Day 7",
    krillOilResult: "−20.3% (mean 2.75)",
    placeboResult: "−17.5% (mean 3.35)",
    statisticalResult: "p = 0.001",
    significance: "Significant",
  },
  {
    study: "Deutsch (2007)",
    journal: "J Am Coll Nutr",
    year: 2007,
    n: 90,
    dose: "300 mg/day",
    duration: "30 days",
    outcomeMeasure: "WOMAC Stiffness",
    timepoint: "Day 30",
    krillOilResult: "−39.1% (mean 2.10)",
    placeboResult: "+4.2% (mean 2.97)",
    statisticalResult: "p = 0.023",
    significance: "Significant",
  },
  {
    study: "Deutsch (2007)",
    journal: "J Am Coll Nutr",
    year: 2007,
    n: 90,
    dose: "300 mg/day",
    duration: "30 days",
    outcomeMeasure: "WOMAC Functional Impairment",
    timepoint: "Day 7",
    krillOilResult: "−22.8% (mean 2.58)",
    placeboResult: "−1.3% (mean 2.94)",
    statisticalResult: "p = 0.008",
    significance: "Significant",
  },
  {
    study: "Deutsch (2007)",
    journal: "J Am Coll Nutr",
    year: 2007,
    n: 90,
    dose: "300 mg/day",
    duration: "30 days",
    outcomeMeasure: "WOMAC Functional Impairment",
    timepoint: "Day 30",
    krillOilResult: "−35.9% (mean 2.14)",
    placeboResult: "−6.7% (mean 2.78)",
    statisticalResult: "p = 0.005",
    significance: "Significant",
  },
  {
    study: "Deutsch (2007)",
    journal: "J Am Coll Nutr",
    year: 2007,
    n: 90,
    dose: "300 mg/day",
    duration: "30 days",
    outcomeMeasure: "Acetaminophen use",
    timepoint: "Day 30",
    krillOilResult: "−31.6%",
    placeboResult: "Reference",
    statisticalResult: "p = 0.012",
    significance: "Significant",
  },
  {
    study: "Suzuki et al. (2016)",
    journal: "PLoS ONE",
    year: 2016,
    n: 50,
    dose: "2 g/day (240 mg EPA + 110 mg DHA)",
    duration: "30 days",
    outcomeMeasure: "JKOM Q3 — Night pain (GLM-adjusted)",
    timepoint: "30 days",
    krillOilResult: "LEmean −1.03",
    placeboResult: "LEmean +1.01",
    statisticalResult: "p < 0.001",
    significance: "Significant",
  },
  {
    study: "Suzuki et al. (2016)",
    journal: "PLoS ONE",
    year: 2016,
    n: 50,
    dose: "2 g/day (240 mg EPA + 110 mg DHA)",
    duration: "30 days",
    outcomeMeasure: "JKOM Q8 — Pain on standing (GLM-adjusted)",
    timepoint: "30 days",
    krillOilResult: "LEmean −1.03",
    placeboResult: "LEmean +0.73",
    statisticalResult: "p < 0.001",
    significance: "Significant",
  },
  {
    study: "Suzuki et al. (2016)",
    journal: "PLoS ONE",
    year: 2016,
    n: 50,
    dose: "2 g/day (240 mg EPA + 110 mg DHA)",
    duration: "30 days",
    outcomeMeasure: "JOA Range of motion — right knee",
    timepoint: "30 days",
    krillOilResult: "Improved",
    placeboResult: "Reference",
    statisticalResult: "p = 0.011",
    significance: "Significant",
  },
  {
    study: "Suzuki et al. (2016)",
    journal: "PLoS ONE",
    year: 2016,
    n: 50,
    dose: "2 g/day (240 mg EPA + 110 mg DHA)",
    duration: "30 days",
    outcomeMeasure: "JOA Range of motion — left knee",
    timepoint: "30 days",
    krillOilResult: "Improved",
    placeboResult: "Reference",
    statisticalResult: "p = 0.011",
    significance: "Significant",
  },
  {
    study: "Suzuki et al. (2016)",
    journal: "PLoS ONE",
    year: 2016,
    n: 50,
    dose: "2 g/day (240 mg EPA + 110 mg DHA)",
    duration: "30 days",
    outcomeMeasure: "JKOM VAS degree of pain",
    timepoint: "30 days",
    krillOilResult: "Mean 1.71 (from 3.40)",
    placeboResult: "Mean 2.14 (from 3.48)",
    statisticalResult: "p = 0.440",
    significance: "Not Significant",
  },
  {
    study: "Suzuki et al. (2016)",
    journal: "PLoS ONE",
    year: 2016,
    n: 50,
    dose: "2 g/day (240 mg EPA + 110 mg DHA)",
    duration: "30 days",
    outcomeMeasure: "Plasma EPA (between groups)",
    timepoint: "30 days",
    krillOilResult: "Increased",
    placeboResult: "Decreased",
    statisticalResult: "p = 0.007",
    significance: "Significant",
  },
  {
    study: "Suzuki et al. (2016)",
    journal: "PLoS ONE",
    year: 2016,
    n: 50,
    dose: "2 g/day (240 mg EPA + 110 mg DHA)",
    duration: "30 days",
    outcomeMeasure: "Plasma EPA/AA ratio (between groups)",
    timepoint: "30 days",
    krillOilResult: "Increased",
    placeboResult: "Decreased",
    statisticalResult: "p = 0.040",
    significance: "Significant",
  },
  {
    study: "Suzuki et al. (2016)",
    journal: "PLoS ONE",
    year: 2016,
    n: 50,
    dose: "2 g/day (240 mg EPA + 110 mg DHA)",
    duration: "30 days",
    outcomeMeasure: "Plasma AA",
    timepoint: "30 days",
    krillOilResult: "Decreased (p = 0.004 within group)",
    placeboResult: "Stable",
    statisticalResult: "Between groups NS",
    significance: "Not Significant",
  },
  {
    study: "Suzuki et al. (2016)",
    journal: "PLoS ONE",
    year: 2016,
    n: 50,
    dose: "2 g/day (240 mg EPA + 110 mg DHA)",
    duration: "30 days",
    outcomeMeasure: "Serum CRP",
    timepoint: "30 days",
    krillOilResult: "No significant change",
    placeboResult: "No significant change",
    statisticalResult: "NS",
    significance: "Not Significant",
  },
  {
    study: "Suzuki et al. (2016)",
    journal: "PLoS ONE",
    year: 2016,
    n: 50,
    dose: "2 g/day (240 mg EPA + 110 mg DHA)",
    duration: "30 days",
    outcomeMeasure: "Serum hyaluronic acid",
    timepoint: "30 days",
    krillOilResult: "Decreased (trend)",
    placeboResult: "Increased (trend)",
    statisticalResult: "Directionally consistent; not formally significant",
    significance: "Not Significant",
  },
  {
    study: "Stonehouse et al. (2022)",
    journal: "Am J Clin Nutr",
    year: 2022,
    n: 235,
    dose: "4 g/day (~0.60 g EPA + 0.28 g DHA + 0.45 mg astaxanthin)",
    duration: "6 months",
    outcomeMeasure: "WOMAC Pain — primary ITT (ANCOVA)",
    timepoint: "6 months",
    krillOilResult: "−17.8 (95% CI −21.2 to −14.4)",
    placeboResult: "−12.6 (95% CI −16.0 to −9.2)",
    statisticalResult: "MD −5.18 (95% CI −10.0 to −0.32); p = 0.04",
    significance: "Significant",
  },
  {
    study: "Stonehouse et al. (2022)",
    journal: "Am J Clin Nutr",
    year: 2022,
    n: 235,
    dose: "4 g/day (~0.60 g EPA + 0.28 g DHA + 0.45 mg astaxanthin)",
    duration: "6 months",
    outcomeMeasure: "WOMAC Stiffness — ITT",
    timepoint: "6 months",
    krillOilResult: "Greater reduction",
    placeboResult: "Reference",
    statisticalResult: "MD −6.45 (95% CI −12.1 to −0.9); p = 0.001",
    significance: "Significant",
  },
  {
    study: "Stonehouse et al. (2022)",
    journal: "Am J Clin Nutr",
    year: 2022,
    n: 235,
    dose: "4 g/day (~0.60 g EPA + 0.28 g DHA + 0.45 mg astaxanthin)",
    duration: "6 months",
    outcomeMeasure: "WOMAC Physical Function — ITT",
    timepoint: "6 months",
    krillOilResult: "Greater improvement",
    placeboResult: "Reference",
    statisticalResult: "MD −4.67 (95% CI −9.26 to −0.05); p < 0.05",
    significance: "Significant",
  },
  {
    study: "Stonehouse et al. (2022)",
    journal: "Am J Clin Nutr",
    year: 2022,
    n: 235,
    dose: "4 g/day (~0.60 g EPA + 0.28 g DHA + 0.45 mg astaxanthin)",
    duration: "6 months",
    outcomeMeasure: "Omega-3 Index",
    timepoint: "6 months",
    krillOilResult: "6.0% → 8.9% (Δ+3.22%; 95% CI 2.96–3.48%)",
    placeboResult: "5.5% → 5.4% (stable)",
    statisticalResult: "p < 0.001",
    significance: "Significant",
  },
  {
    study: "Stonehouse et al. (2022)",
    journal: "Am J Clin Nutr",
    year: 2022,
    n: 235,
    dose: "4 g/day (~0.60 g EPA + 0.28 g DHA + 0.45 mg astaxanthin)",
    duration: "6 months",
    outcomeMeasure: "WOMAC Pain — high inflammation subgroup",
    timepoint: "6 months",
    krillOilResult: "Greater effect than overall",
    placeboResult: "Reference",
    statisticalResult: "MD −20 (95% CI −10 to −31); interaction p = 0.01",
    significance: "Significant",
  },
  {
    study: "Stonehouse et al. (2022)",
    journal: "Am J Clin Nutr",
    year: 2022,
    n: 235,
    dose: "4 g/day (~0.60 g EPA + 0.28 g DHA + 0.45 mg astaxanthin)",
    duration: "6 months",
    outcomeMeasure: "hsCRP",
    timepoint: "6 months",
    krillOilResult: "−0.3% change",
    placeboResult: "−3.3% change",
    statisticalResult: "p = 0.72",
    significance: "Not Significant",
  },
  {
    study: "Stonehouse et al. (2022)",
    journal: "Am J Clin Nutr",
    year: 2022,
    n: 235,
    dose: "4 g/day (~0.60 g EPA + 0.28 g DHA + 0.45 mg astaxanthin)",
    duration: "6 months",
    outcomeMeasure: "IL-6",
    timepoint: "6 months",
    krillOilResult: "+195%",
    placeboResult: "+169%",
    statisticalResult: "p = 0.90",
    significance: "Not Significant",
  },
  {
    study: "Stonehouse et al. (2022)",
    journal: "Am J Clin Nutr",
    year: 2022,
    n: 235,
    dose: "4 g/day (~0.60 g EPA + 0.28 g DHA + 0.45 mg astaxanthin)",
    duration: "6 months",
    outcomeMeasure: "TNF-α",
    timepoint: "6 months",
    krillOilResult: "+5.4%",
    placeboResult: "−2.2%",
    statisticalResult: "p = 0.52",
    significance: "Not Significant",
  },
  {
    study: "Stonehouse et al. (2022)",
    journal: "Am J Clin Nutr",
    year: 2022,
    n: 235,
    dose: "4 g/day (~0.60 g EPA + 0.28 g DHA + 0.45 mg astaxanthin)",
    duration: "6 months",
    outcomeMeasure: "Serum triglycerides",
    timepoint: "6 months",
    krillOilResult: "−3.3%",
    placeboResult: "+0.6%",
    statisticalResult: "p = 0.37",
    significance: "Not Significant",
  },
  {
    study: "Stonehouse et al. (2022)",
    journal: "Am J Clin Nutr",
    year: 2022,
    n: 235,
    dose: "4 g/day (~0.60 g EPA + 0.28 g DHA + 0.45 mg astaxanthin)",
    duration: "6 months",
    outcomeMeasure: "LDL cholesterol",
    timepoint: "3 months",
    krillOilResult: "+0.17 mmol/L",
    placeboResult: "-0.03 mmol/L",
    statisticalResult: "MD 0.20 (p = 0.01) — transient",
    significance: "Not Significant (transient)",
  },
  {
    study: "Stonehouse et al. (2022)",
    journal: "Am J Clin Nutr",
    year: 2022,
    n: 235,
    dose: "4 g/day (~0.60 g EPA + 0.28 g DHA + 0.45 mg astaxanthin)",
    duration: "6 months",
    outcomeMeasure: "NSAID use",
    timepoint: "6 months",
    krillOilResult: "No significant difference",
    placeboResult: "Reference",
    statisticalResult: "NS",
    significance: "Not Significant",
  },
  {
    study: "Laslett et al. (2024)",
    journal: "JAMA",
    year: 2024,
    n: 262,
    dose: "2 g/day",
    duration: "24 weeks",
    outcomeMeasure: "VAS Knee Pain — primary ITT",
    timepoint: "24 weeks",
    krillOilResult: "No significant change",
    placeboResult: "Reference",
    statisticalResult: "MD 0.30 (95% CI −6.9 to 6.4); p = 0.94",
    significance: "Not Significant",
  },
  {
    study: "Laslett et al. (2024)",
    journal: "JAMA",
    year: 2024,
    n: 262,
    dose: "2 g/day",
    duration: "24 weeks",
    outcomeMeasure: "MRI effusion-synovitis volume",
    timepoint: "24 weeks",
    krillOilResult: "No significant change",
    placeboResult: "Reference",
    statisticalResult: "NS",
    significance: "Not Significant",
  },
  {
    study: "Laslett et al. (2024)",
    journal: "JAMA",
    year: 2024,
    n: 262,
    dose: "2 g/day",
    duration: "24 weeks",
    outcomeMeasure: "WOMAC Pain",
    timepoint: "24 weeks",
    krillOilResult: "No significant difference",
    placeboResult: "Reference",
    statisticalResult: "NS",
    significance: "Not Significant",
  },
  {
    study: "Laslett et al. (2024)",
    journal: "JAMA",
    year: 2024,
    n: 262,
    dose: "2 g/day",
    duration: "24 weeks",
    outcomeMeasure: "WOMAC Stiffness",
    timepoint: "24 weeks",
    krillOilResult: "No significant difference",
    placeboResult: "Reference",
    statisticalResult: "NS",
    significance: "Not Significant",
  },
  {
    study: "Laslett et al. (2024)",
    journal: "JAMA",
    year: 2024,
    n: 262,
    dose: "2 g/day",
    duration: "24 weeks",
    outcomeMeasure: "WOMAC Physical Function",
    timepoint: "24 weeks",
    krillOilResult: "No significant difference",
    placeboResult: "Reference",
    statisticalResult: "NS",
    significance: "Not Significant",
  },
  {
    study: "Laslett et al. (2024)",
    journal: "JAMA",
    year: 2024,
    n: 262,
    dose: "2 g/day",
    duration: "24 weeks",
    outcomeMeasure: "Omega-3 Index",
    timepoint: "24 weeks",
    krillOilResult: "Significant increase (confirms adherence)",
    placeboResult: "Stable",
    statisticalResult: "p < 0.001",
    significance: "Significant",
  },
  {
    study: "Laslett et al. (2024)",
    journal: "JAMA",
    year: 2024,
    n: 262,
    dose: "2 g/day",
    duration: "24 weeks",
    outcomeMeasure: "Adverse events",
    timepoint: "24 weeks",
    krillOilResult: "No difference from placebo",
    placeboResult: "Reference",
    statisticalResult: "Safe and well-tolerated",
    significance: "Not Significant",
  },
  {
    study: "Andersen et al. (2026)*",
    journal: "Protocol — FICTIVE",
    year: 2026,
    n: "320 (target)",
    dose: "4 g/day (~0.8 g EPA + 0.36 g DHA, phospholipid-bound)",
    duration: "12 months",
    outcomeMeasure: "WOMAC Pain (primary)",
    timepoint: "12 months",
    krillOilResult: "Pending",
    placeboResult: "Pending",
    statisticalResult: "Target: MD ≥15 points (MCID); 90% power",
    significance: "Pending",
  },
  {
    study: "Andersen et al. (2026)*",
    journal: "Protocol — FICTIVE",
    year: 2026,
    n: "320 (target)",
    dose: "4 g/day (~0.8 g EPA + 0.36 g DHA, phospholipid-bound)",
    duration: "12 months",
    outcomeMeasure: "WOMAC Stiffness",
    timepoint: "12 months",
    krillOilResult: "Pending",
    placeboResult: "Pending",
    statisticalResult: "Pre-specified secondary",
    significance: "Pending",
  },
  {
    study: "Andersen et al. (2026)*",
    journal: "Protocol — FICTIVE",
    year: 2026,
    n: "320 (target)",
    dose: "4 g/day (~0.8 g EPA + 0.36 g DHA, phospholipid-bound)",
    duration: "12 months",
    outcomeMeasure: "WOMAC Physical Function",
    timepoint: "12 months",
    krillOilResult: "Pending",
    placeboResult: "Pending",
    statisticalResult: "Pre-specified secondary",
    significance: "Pending",
  },
  {
    study: "Andersen et al. (2026)*",
    journal: "Protocol — FICTIVE",
    year: 2026,
    n: "320 (target)",
    dose: "4 g/day (~0.8 g EPA + 0.36 g DHA, phospholipid-bound)",
    duration: "12 months",
    outcomeMeasure: "MRI synovial volume",
    timepoint: "6 & 12 months",
    krillOilResult: "Pending",
    placeboResult: "Pending",
    statisticalResult: "Pre-specified sub-study endpoint",
    significance: "Pending",
  },
  {
    study: "Andersen et al. (2026)*",
    journal: "Protocol — FICTIVE",
    year: 2026,
    n: "320 (target)",
    dose: "4 g/day (~0.8 g EPA + 0.36 g DHA, phospholipid-bound)",
    duration: "12 months",
    outcomeMeasure: "Serum hsCRP",
    timepoint: "3, 6 & 12 months",
    krillOilResult: "Pending",
    placeboResult: "Pending",
    statisticalResult: "Pre-specified sub-study",
    significance: "Pending",
  },
  {
    study: "Andersen et al. (2026)*",
    journal: "Protocol — FICTIVE",
    year: 2026,
    n: "320 (target)",
    dose: "4 g/day (~0.8 g EPA + 0.36 g DHA, phospholipid-bound)",
    duration: "12 months",
    outcomeMeasure: "Serum IL-6",
    timepoint: "3, 6 & 12 months",
    krillOilResult: "Pending",
    placeboResult: "Pending",
    statisticalResult: "Pre-specified sub-study",
    significance: "Pending",
  },
  {
    study: "Andersen et al. (2026)*",
    journal: "Protocol — FICTIVE",
    year: 2026,
    n: "320 (target)",
    dose: "4 g/day (~0.8 g EPA + 0.36 g DHA, phospholipid-bound)",
    duration: "12 months",
    outcomeMeasure: "Serum TNF-α",
    timepoint: "3, 6 & 12 months",
    krillOilResult: "Pending",
    placeboResult: "Pending",
    statisticalResult: "Pre-specified sub-study",
    significance: "Pending",
  },
  {
    study: "Andersen et al. (2026)*",
    journal: "Protocol — FICTIVE",
    year: 2026,
    n: "320 (target)",
    dose: "4 g/day (~0.8 g EPA + 0.36 g DHA, phospholipid-bound)",
    duration: "12 months",
    outcomeMeasure: "Serum MMP-3",
    timepoint: "3, 6 & 12 months",
    krillOilResult: "Pending",
    placeboResult: "Pending",
    statisticalResult: "Pre-specified sub-study",
    significance: "Pending",
  },
  {
    study: "Andersen et al. (2026)*",
    journal: "Protocol — FICTIVE",
    year: 2026,
    n: "320 (target)",
    dose: "4 g/day (~0.8 g EPA + 0.36 g DHA, phospholipid-bound)",
    duration: "12 months",
    outcomeMeasure: "Omega-3 Index",
    timepoint: "6 & 12 months",
    krillOilResult: "Pending",
    placeboResult: "Pending",
    statisticalResult: "Adherence marker",
    significance: "Pending",
  },
  {
    study: "Andersen et al. (2026)*",
    journal: "Protocol — FICTIVE",
    year: 2026,
    n: "320 (target)",
    dose: "4 g/day (~0.8 g EPA + 0.36 g DHA, phospholipid-bound)",
    duration: "12 months",
    outcomeMeasure: "EQ-5D-5L quality of life",
    timepoint: "12 months",
    krillOilResult: "Pending",
    placeboResult: "Pending",
    statisticalResult: "Pre-specified secondary",
    significance: "Pending",
  },
];

export const WAREHOUSE_OUTCOMES: WarehouseOutcome[] = [
  {
    study: "Deutsch (2007)",
    year: 2007,
    n: 90,
    population: "CVD/RA/OA with elevated CRP",
    dose: "300 mg/day",
    duration: "30 days",
    primaryOutcomeMeasure: "CRP + WOMAC (pain, stiffness, function)",
    directionOfEffect: "Favours krill oil",
    pValue: "p<0.001 (CRP)",
    conclusion: "Significant improvement across CRP and all WOMAC domains; low methodological quality",
  },
  {
    study: "Suzuki et al. (2016)",
    year: 2016,
    n: 50,
    population: "Mild knee pain (no pharmacotherapy)",
    dose: "2 g/day",
    duration: "30 days",
    primaryOutcomeMeasure: "JKOM & JOA symptom scores",
    directionOfEffect: "Favours krill oil",
    pValue: "p<0.001 (selected subscores)",
    conclusion: "Significant night pain and standing pain relief; range of motion improved; small sample, non-ITT",
  },
  {
    study: "Stonehouse et al. (2022)",
    year: 2022,
    n: 235,
    population: "Mild–moderate knee OA (VAS 4–8/10)",
    dose: "4 g/day",
    duration: "6 months",
    primaryOutcomeMeasure: "WOMAC knee pain at 6 months",
    directionOfEffect: "Favours krill oil",
    pValue: "MD −5.18 (p=0.04)",
    conclusion: "Significant pain, stiffness & function improvement; Omega-3 Index 6%→9%; high quality",
  },
  {
    study: "Laslett et al. (2024)",
    year: 2024,
    n: 262,
    population: "Knee OA + significant pain + effusion-synovitis on MRI",
    dose: "2 g/day",
    duration: "24 weeks",
    primaryOutcomeMeasure: "VAS knee pain (0–100) over 24 weeks",
    directionOfEffect: "No effect",
    pValue: "MD 0.30 (p=0.94)",
    conclusion: "No benefit at 2 g/day in this specific population; Omega-3 Index confirmed adherence",
  },
  {
    study: "Andersen et al. (2026)*",
    year: 2026,
    n: "320 (target)",
    population: "Knee OA + elevated hsCRP + MRI synovial thickening",
    dose: "4 g/day",
    duration: "12 months",
    primaryOutcomeMeasure: "WOMAC knee pain (0–100) at 12 months",
    directionOfEffect: "Pending (optimistic hypothesis)",
    pValue: "Protocol only",
    conclusion: "FICTIVE — powered to detect MCID ≥15 pts (90%); biomarker sub-study planned",
  },
];

export const WAREHOUSE_QUALITY_STUDIES: string[] = ["Deutsch (2007)", "Suzuki et al. (2016)", "Stonehouse et al. (2022)", "Laslett et al. (2024)", "Andersen et al. (2026)*"];

export const WAREHOUSE_QUALITY_CRITERIA: WarehouseQualityCriterion[] = [
  {
    criterion: "Randomisation reported",
    values: {"Deutsch (2007)": "Yes", "Suzuki et al. (2016)": "Yes", "Stonehouse et al. (2022)": "Yes", "Laslett et al. (2024)": "Yes", "Andersen et al. (2026)*": "Yes"},
  },
  {
    criterion: "Blinding (double-blind)",
    values: {"Deutsch (2007)": "Yes", "Suzuki et al. (2016)": "Yes", "Stonehouse et al. (2022)": "Yes", "Laslett et al. (2024)": "Yes", "Andersen et al. (2026)*": "Yes"},
  },
  {
    criterion: "Allocation concealment",
    values: {"Deutsch (2007)": "No/NR", "Suzuki et al. (2016)": "No/NR", "Stonehouse et al. (2022)": "Yes", "Laslett et al. (2024)": "Yes", "Andersen et al. (2026)*": "Yes"},
  },
  {
    criterion: "ITT analysis",
    values: {"Deutsch (2007)": "No/NR", "Suzuki et al. (2016)": "No/NR", "Stonehouse et al. (2022)": "Yes", "Laslett et al. (2024)": "Yes", "Andersen et al. (2026)*": "Yes"},
  },
  {
    criterion: "Dropout/withdrawal reported",
    values: {"Deutsch (2007)": "No/NR", "Suzuki et al. (2016)": "Yes", "Stonehouse et al. (2022)": "Yes", "Laslett et al. (2024)": "Yes", "Andersen et al. (2026)*": "Yes"},
  },
  {
    criterion: "Trial registration",
    values: {"Deutsch (2007)": "No/NR", "Suzuki et al. (2016)": "Yes", "Stonehouse et al. (2022)": "Yes", "Laslett et al. (2024)": "Yes", "Andersen et al. (2026)*": "No/NR"},
  },
  {
    criterion: "Sample size calculation",
    values: {"Deutsch (2007)": "No/NR", "Suzuki et al. (2016)": "No/NR", "Stonehouse et al. (2022)": "Yes", "Laslett et al. (2024)": "Yes", "Andersen et al. (2026)*": "Yes"},
  },
  {
    criterion: "Funding transparency",
    values: {"Deutsch (2007)": "No/NR", "Suzuki et al. (2016)": "Yes", "Stonehouse et al. (2022)": "Yes", "Laslett et al. (2024)": "Yes", "Andersen et al. (2026)*": "Yes"},
  },
  {
    criterion: "Quality Score (%)",
    values: {"Deutsch (2007)": 25, "Suzuki et al. (2016)": 62.5, "Stonehouse et al. (2022)": 100, "Laslett et al. (2024)": 100, "Andersen et al. (2026)*": 87.5},
  },
];

